### ISSUE TITLE
Add unread notifications to tray icon

### ISSUE THREAD

**Issue by twolfson** [wlaurance/slack-for-linux#15]
It would be nice to see unread message notifications in the tray icon. We can leverage a favicon library like http://lab.ejci.net/favico.js/ to perform the badge overlay.

![Unread notification message](https://cloud.githubusercontent.com/assets/902488/5595192/b21a773a-9231-11e4-8da9-3bf2159f3f40.png)

**Comment by twolfson** [comment]
I have completed this but am waiting on an issue to be resolved in a dependant repo.

https://github.com/ejci/favico.js/issues/54

The finished product can be found in `twolfson/slack-for-linux#dev/add.favicon.notifications`:

https://github.com/twolfson/slack-for-linux/compare/70707697124614d7dd093390444d6bdb50ce7dc8

For the reference of myself and future developers, here are notes:

I started by creating the `slack-for-linux-test` organization. Anyone can sign up with a mailinator.com (disposable mail service):

https://slack-for-linux-test.slack.com/

http://mailinator.com/

After that, I began digging around in the Slack source code. I found:

http://viewsource.in/https://slack.global.ssl.fastly.net/31971/js/rollup-client_1420067921.js#L473

```js
TS.channels.unread_changed_sig.add(TS.view.channelUnreadCountChanged,TS.view);
```

which was very promising. It was an observer pattern that published on an unread update change for any channel. There were similar surrounding lines for `ims`.

Next, I had to determine how to read this data. After some more digging, I found some model data which I forgot to write down (`TS.ui.something.unread_highlight_count`). This lead me to my next big item:

http://viewsource.in/https://slack.global.ssl.fastly.net/31971/js/rollup-client_1420067921.js#L6497-6506

```js
// TS.ui.growls.updateTotalUnreadDisplays
updateTotalUnreadDisplays: function() {
  if (window.macgap || window.winssb) {
    TSSSB.call("setBadgeCount", {
      all_unread_highlights_cnt: TS.model.all_unread_highlights_cnt,
      all_unread_cnt: TS.model.all_unread_cnt,
      bullet: (window.macgap) ? !!TS.model.prefs.mac_ssb_bullet : !!TS.model.prefs.win_ssb_bullet
    })
  }
  if (window.fluid) {
    if (TS.model.all_unread_highlights_cnt + TS.model.all_unread_cnt) {
      var a = TS.model.all_unread_highlights_cnt;
      if (a > 9) {
        a = "9+"
      }
      if (!a) {
        a = (TS.model.prefs.mac_ssb_bullet) ? "•" : ""
      }
      if (window.fluid) {
        window.fluid.dockBadge = a.toString()
      }
    } else {
      if (window.fluid) {
        window.fluid.dockBadge = ""
      }
    }
  }
  if (TS.model.all_unread_highlights_cnt) {
    TS.view.changeUnreadStatus("mentions")
  } else {
    if (TS.model.all_unread_cnt) {
      TS.view.changeUnreadStatus("unreads")
    } else {
      TS.view.changeUnreadStatus("")
    }
  }
}
```

After that, I found the last piece which is the bindings for the growls themself. We cannot leverage the growl since these are configured inside of Slack. However, we can use their observers.

http://viewsource.in/https://slack.global.ssl.fastly.net/31971/js/rollup-client_1420067921.js#L6413-6419

```js
TS.channels.unread_changed_sig.add(TS.ui.growls.updateTotalUnreadDisplays,TS.ui.growls);
TS.channels.unread_highlight_changed_sig.add(TS.ui.growls.updateTotalUnreadDisplays,TS.ui.growls);
TS.groups.unread_changed_sig.add(TS.ui.growls.updateTotalUnreadDisplays,TS.ui.growls);
TS.groups.unread_highlight_changed_sig.add(TS.ui.growls.updateTotalUnreadDisplays,TS.ui.growls);
TS.ims.unread_changed_sig.add(TS.ui.growls.updateTotalUnreadDisplays,TS.ui.growls);
TS.ims.unread_highlight_changed_sig.add(TS.ui.growls.updateTotalUnreadDisplays,TS.ui.growls);
TS.client.login_sig.add(TS.ui.growls.updateTotalUnreadDisplays,TS.ui.growls);
```

**Comment by kellevan** [comment]
Looks like the dependency is stalled - has any progress been made on notifications?

Awesome app guys, works wonderfully.

**Comment by twolfson** [comment]
I have been using it personally since the submission of this PR and it has been great with no hiccups. I will bump the issue again. Worst case scenario: We can consider forking, using a `git` dependency, or another library.

**Comment by twolfson** [comment]
A PR has finally been opened. Hopefully it won't take long to land this and get it in your hands =)
