### ISSUE TITLE
Unable to install on ubuntu 14.10

### ISSUE THREAD

**Issue by geertpeeters** [wlaurance/slack-for-linux#18]
I tried to install this interesting project to have a native Slack client on my Ubuntu 14.10

I received an error during post install : 
I'm not a nodejs expert at all.
Ran the command as root

npm install slack-for-linux -g
/usr/local/bin/slack-for-linux -> /usr/local/lib/node_modules/slack-for-linux/run.js

> slack-for-linux@1.2.0 postinstall /usr/local/lib/node_modules/slack-for-linux
> ./install.sh

npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! slack-for-linux@1.2.0 postinstall: `./install.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the slack-for-linux@1.2.0 postinstall script.
npm ERR! This is most likely a problem with the slack-for-linux package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./install.sh
npm ERR! You can get their info via:
npm ERR!     npm owner ls slack-for-linux
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.16.0-31-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "slack-for-linux" "-g"
npm ERR! cwd /tmp
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /tmp/npm-debug.log
npm ERR! not ok code 0

**npm version : 1.4.21**

**Comment by twolfson** [comment]
You seem to be on an old version of `npm`. Can you try upgrading and installing after that?

```bash
npm install npm@latest -g
```

**Comment by madmuffin1** [comment]
Yes, that should do the trick. I'm running latest node on Ubuntu 14.10, I was able to install slack-for-linux on both of my machines.

**Comment by wlaurance** [comment]
@geertpeeters Still having any difficulties?
