### ISSUE TITLE
Downloading files from within Slack will result empty Slack window

### ISSUE THREAD

**Issue by madmuffin1** [wlaurance/slack-for-linux#25]
When clicking on a file link "Open original in new window" in the right hand file pane, the main window will switch to an empty view and will open the file save dialog.

Even when saving that file, the window's content would stay blank. Using Alt-Left or Backspace or the back-button on my mouse do not work.

Workaround: Close and reopen slack-for-linux after downloading a file.

**Comment by twolfson** [comment]
iirc, another workaround should be Shift+Clicking the link to force it to open in a new window. I will take a look by the end of next weekend.

**Comment by twolfson** [comment]
I have looked into the issue. Our new window policy was being too conservative. I am opening a PR to show download dialogs for these kinds of files (i.e. ones hosted on `files.slack.com`) and opening any other ones in a browser.

![selection_115](https://cloud.githubusercontent.com/assets/902488/6958210/6e17a920-d8ce-11e4-894e-106afe7decf3.png)

**Comment by twolfson** [comment]
Aaand the PR is now open, #25 for reference.

**Comment by madmuffin1** [comment]
Wow, thanks a lot!
