### ISSUE TITLE
Tag and push latest to npm

### ISSUE THREAD

**Issue by andrewelkins** [wlaurance/slack-for-linux#36]
Can we get the latest tagged and pushed to npm?

**Comment by wlaurance** [comment]
1.3.0 has been published.

**Comment by wlaurance** [comment]
But it doesn't have the team support in it yet. Working on merging that one in.

**Comment by twolfson** [comment]
As a heads up, we missed a `git tag` as well =/

**Comment by wlaurance** [comment]
forgot to push --tags, done now.

**Comment by wlaurance** [comment]
@andrewelkins 1.4 is tagged and published.

**Comment by andrewelkins** [comment]
Thanks!! It's working great!!
