### ISSUE TITLE
Sign back in to last team on relaunch

### ISSUE THREAD

**Issue by twolfson** [wlaurance/slack-for-linux#4]
When relaunching `slack-for-linux`, it is frustrating to not be automatically logged back in to my team. Can we add an `.on('close')` trigger that saves the hostname for relaunch? We would need to start creating a `~/.config/slack-for-linux.json` or similar for this to work.

https://github.com/rogerwang/node-webkit/wiki/Window#close

**Comment by wlaurance** [comment]
This has been merged and released.
