### ISSUE TITLE
Minimizing to tray doesn't work on Kubuntu 15.04

### ISSUE THREAD

**Issue by Grief** [wlaurance/slack-for-linux#48]
If I create an advanced rule for the window based on title match ('slack-for-linux', hope it is never changed), I can remove it from taskbar, but then, if I would minimize the window, I cannot restore it from tray icon.

**Comment by twolfson** [comment]
I don't fully understand. What is this advanced rule and what is it doing?

**Comment by Grief** [comment]
It's from KDE systemsettings. The correct English name must be "special window settings". It provides different abilities like as hiding a window from being shown in task bar.

**Comment by twolfson** [comment]
Okay, cool. Does minimizing/restoring via the tray icon without setting that advanced rule?

**Comment by Grief** [comment]
It just minimizes/restores from/to taskbar

**Comment by twolfson** [comment]
Ah, right. Yea, it sounds like this is something between KDE and `nw.js`, not really in the scope of `slack-for-linux` =/

Can you open an issue here: https://github.com/nwjs/nw.js/issues ?

**Comment by twolfson** [comment]
@Grief What was the resolution to the issue?

**Comment by Grief** [comment]
@twolfson The issue comes from Chromium, nw.js just uses it underneath. I don't think that they will fix that soon as actually there is currently no application supporting this new API. It's a claim to KDE team for breaking backward compatibility.

**Comment by Mte90** [comment]
same problem on debian with kde :-(
