### ISSUE TITLE
Switch from JS launcher to sh launcher

### ISSUE THREAD

**Issue by twolfson** [wlaurance/slack-for-linux#6]
Currently, we are using `sh` (despite a lacking shebang) for our `postinstall` script. I noticed in my `ps` output that `slack-for-linux` is running behind `node`. This can cause frustration if I use `pkill node` (sometimes zombie processes need to be killed).

An additional side effect is that the `spawn` call currently does not output `stdout` or `stderr` (usually via `stdio` option). To prevent and future one-off issues, I suggest moving off of a JS launcher for `run.sh` and onto a `sh` based one.

```sh
#!/usr/bin/env sh
./webkitbuilds/slack4linux/linux64/slack4linux
```

**Comment by wlaurance** [comment]
This issue has two problems.

1. `pkill node` will kill off slack-for-linux. If you are developing in node, this is a bad thing.

2. The logs are consumed

For 1, #42 allows us to rename the process name to 'slack-for-linux' and 'pkill node' or 'killall node' doesn't affect this application.

As for problem 2, I think we should provide all logging information to stderr and stdout. Then the user of this app will deal with the logs themselves.

@twolfson

**Comment by twolfson** [comment]
If anything was vulnerable to `pkill node`, it would be this current setup which is running `node`. `pkill node` won't discover `nw.js` since it has been renamed to `nw`.

We should probably have a deeper discussion regarding logging. I think `stderr`/`stdout` are fine but we should probably log to disk as well (e.g. `~/.slack-for-linux/info.log`). It will help for any users that start the application via a Desktop Application.

**Comment by twolfson** [comment]
After further thought, JS is preferred due to keeping CLI parsing/handling consistent. Closing this issue.
